<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE spec [
    <!ELEMENT spec (auxfiles?, name, shortname?, toc)>
    <!ATTLIST spec id CDATA #REQUIRED>
    <!ATTLIST spec variant CDATA #REQUIRED>
    <!ATTLIST spec revision CDATA #REQUIRED>
    <!ATTLIST spec lang CDATA #REQUIRED>
    <!ATTLIST spec version CDATA #REQUIRED>
    <!ATTLIST spec nopreviews CDATA #IMPLIED>
    <!ATTLIST spec xmlns CDATA #FIXED "http://apple.com/ns/spec/v1">
    <!ATTLIST spec accsys CDATA #FIXED "http://apple.com/ns/accsys/v1">
    <!ELEMENT auxfiles (file)*>
    <!ELEMENT file EMPTY>
    <!ATTLIST file type CDATA #FIXED "pdf">
    <!ATTLIST file verifier CDATA #REQUIRED>
    <!ATTLIST file read-info CDATA #IMPLIED>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT shortname (#PCDATA)>
    <!ELEMENT toc (entry)+>
    <!ELEMENT entry (index, name, keywords?, related*, internal?)>
    <!ATTLIST entry label CDATA #REQUIRED>
    <!ATTLIST entry type (section|chapter|figure|table) "section">
    <!ELEMENT index (#PCDATA)>
    <!ELEMENT internal (#PCDATA)>
    <!ELEMENT related (item)*>
    <!ELEMENT item (#PCDATA)>
    <!ELEMENT keywords (#PCDATA)>
]>
<spec revision="29" id="aispec" lang="en-US" accsys="http://apple.com/ns/accsys/v1" nopreviews="0" variant="release" version="1" xmlns="http://apple.com/ns/spec/v1">
<auxfiles>
<file type="pdf" verifier="Accessory,Interface,Specification,Release,R29" read-info="52.0,42.0,508.0,700.0">
</file>
</auxfiles>
<name>Accessory Interface Specification R29</name>
<shortname>
</shortname>
<toc>
<entry label="Introduction" type="chapter">
<index>1</index>
<name>Introduction</name>
<keywords>cryptography,challenging,prohibition,implication,historical,statement,encourage,licensed,trackpad,adoption</keywords>
<related>
<item>spec://Introduction:Requirements/*</item>
<item>spec://Introduction:DeveloperPreview/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11CLK0001</internal>
</entry>
<entry label="Introduction:Purpose" type="section">
<index>1.1</index>
<name>Purpose of This Specification</name>
<keywords>introduction,recommendation,purpose,watch,detail,iphone,interface,requirement,apple</keywords>
<related>
<item>spec://Introduction:Terminology:Accessory/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
<item>spec://Introduction:Terminology:Device/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
<item>spec://Introduction:Terminology:ChallengeResponse/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0002</internal>
</entry>
<entry label="Introduction:Organization" type="section">
<index>1.2</index>
<name>Organization</name>
<keywords>introduction,related,chapter,tool,group,part,component,feature,module,connector</keywords>
<related>
<item>spec://Introduction:Terminology:Accessory/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
<item>spec://Introduction:Terminology:Device/*</item>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0003</internal>
</entry>
<entry label="Introduction:Applicability" type="section">
<index>1.3</index>
<name>Applicability</name>
<keywords>trackpad,introduction,magic,accessory interface,1st,apple tv,apple watch series,5th generation</keywords>
<related>
<item>spec://Introduction:Terminology:Accessory/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
<item>spec://Introduction:Terminology:Device/*</item>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0004</internal>
</entry>
<entry label="Introduction:Requirements" type="section">
<index>1.4</index>
<name>Requirements, Recommendations, and Permissions</name>
<keywords>implication,prohibition,historical,statement,encourage,introduction,licensee,permission,understand</keywords>
<related>
<item>spec://Introduction/*</item>
<item>spec://Introduction:Terminology:Accessory/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
<item>spec://Introduction:Terminology:Device/*</item>
<item>spec://Introduction:Purpose/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0005</internal>
</entry>
<entry label="Introduction:DeveloperPreview" type="section">
<index>1.5</index>
<name>Developer Preview</name>
<keywords>adoption,licensed,introduction,preview,final,documentation,developer,accuracy,development</keywords>
<related>
<item>spec://Introduction:Terminology:Accessory/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
<item>spec://Introduction:Terminology:Device/*</item>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0006</internal>
</entry>
<entry label="Introduction:ManufacturerPreview" type="section">
<index>1.6</index>
<name>Manufacturer Preview</name>
<keywords>introduction,license,preview,develop,propose,manufacturer,final,content,developer</keywords>
<related>
<item>spec://Introduction:Terminology:Accessory/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
<item>spec://Introduction:Terminology:Device/*</item>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0007</internal>
</entry>
<entry label="Introduction:Terminology" type="section">
<index>1.7</index>
<name>Terminology</name>
<keywords>introduction,cryptography,creation,authentication coprocessor,philip,grant,challenging,actuate,possibility,govern</keywords>
<related>
<item>spec://accessoryAll:TestProcedures:OTA:Terminology/*</item>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Organization/*</item>
<item>spec://Introduction:ManufacturerPreview/*</item>
<item>spec://RevisionHistory:UpdatedContent/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0008</internal>
</entry>
<entry label="Introduction:Terminology:Device" type="section">
<index>1.7.1</index>
<name>Device</name>
<keywords>introduction,refer,ipod,specific,product,operate,ipad,ios,system</keywords>
<related>
<item>spec://Introduction:Terminology:Accessory/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
<item>spec://Introduction:Terminology:ChallengeResponse/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0009</internal>
</entry>
<entry label="Introduction:Terminology:Accessory" type="section">
<index>1.7.2</index>
<name>Accessory</name>
<keywords>introduction,refer,describe,product,interface,connect,device</keywords>
<related>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
<item>spec://Introduction:Terminology:Device/*</item>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
<item>spec://Introduction:Terminology:ChallengeResponse/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0010</internal>
</entry>
<entry label="Introduction:Terminology:AuthenticationCoprocessor" type="section">
<index>1.7.3</index>
<name>Authentication Coprocessor</name>
<keywords>introduction,creation,philip,challenging,computation,related,reside,document,easy,signature</keywords>
<related>
<item>spec://Introduction:Terminology:Challenge/*</item>
<item>spec://Introduction:Terminology:Accessory/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
<item>spec://Introduction:Terminology:Device/*</item>
<item>spec://Introduction:Purpose/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0011</internal>
</entry>
<entry label="Introduction:Terminology:I2CBus" type="section">
<index>1.7.4</index>
<name>I^{2}C Bus</name>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0012</internal>
</entry>
<entry label="Introduction:Terminology:Challenge" type="section">
<index>1.7.5</index>
<name>Challenge</name>
<keywords>introduction,challenging,computation,vice,random,verification,offer,result,return,response</keywords>
<related>
<item>spec://Introduction:Terminology:Accessory/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
<item>spec://Introduction:Terminology:Device/*</item>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0013</internal>
</entry>
<entry label="Introduction:Terminology:ChallengeResponse" type="section">
<index>1.7.6</index>
<name>Challenge Response</name>
<keywords>introduction,obtain,offer,challenge,result,response,process,perform,page</keywords>
<related>
<item>spec://Introduction:Terminology:Accessory/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
<item>spec://Introduction:Terminology:Device/*</item>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0014</internal>
</entry>
<entry label="Introduction:Terminology:X509Certificate" type="section">
<index>1.7.7</index>
<name>X.509 Certificate</name>
<keywords>introduction,cryptography,govern,telecommunication,international,identity,public,union,verification,certificarsi</keywords>
<related>
<item>spec://Introduction:Terminology:Accessory/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
<item>spec://Introduction:Terminology:Device/*</item>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0015</internal>
</entry>
<entry label="Introduction:Terminology:Component" type="section">
<index>1.7.8</index>
<name>Component</name>
<keywords>introduction,functional,human,collection,limit,define,data,include,unit,interface</keywords>
<related>
<item>spec://Introduction:Terminology:Accessory/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
<item>spec://Introduction:Terminology:Device/*</item>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:ChallengeResponse/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0016</internal>
</entry>
<entry label="Introduction:Terminology:DUA" type="section">
<index>1.7.9</index>
<name>Direct User Action</name>
<keywords>introduction,grant,actuate,wave,retry,prohibit,affect,task,interact,move</keywords>
<related>
<item>spec://accessoryKeyboards:TestProcedures:DirectUserAction/*</item>
<item>spec://featureCarPlay:GeneralRequirements:Architecture:CarPlayOverWireless:Session%20Termination:Direct%20User%20Action/*</item>
<item>spec://Introduction:Terminology:Accessory/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
<item>spec://Introduction:Terminology:Device/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0017</internal>
</entry>
<entry label="Introduction:Terminology:Feature" type="section">
<index>1.7.10</index>
<name>Feature</name>
<keywords>introduction,possibility,react,account,recommendation,comply,design,implement,specific,requirement</keywords>
<related>
<item>spec://Introduction:Terminology:Accessory/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
<item>spec://Introduction:Terminology:Device/*</item>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0018</internal>
</entry>
<entry label="Introduction:Terminology:USBDeviceandHostMode" type="section">
<index>1.7.11</index>
<name>USB Device Mode and USB Host Mode</name>
<keywords>introduction,usb host,capable,usb device mode,role,ios</keywords>
<related>
<item>spec://Introduction:Terminology:Accessory/*</item>
<item>spec://Introduction:Terminology:Device/*</item>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
<item>spec://Introduction:Terminology:ChallengeResponse/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0019</internal>
</entry>
<entry label="accessoryAll" type="chapter">
<index>2</index>
<name>All Accessories</name>
<keywords>radio frequency,duplication,matrix,proxy,connector modifications,reproducibility,uncertainty,multiple simultaneous</keywords>
<related>
<item>spec://connectorE75:MechanicalRequirements:All/*</item>
<item>spec://connectorC78C79:MechanicalRequirements:All/*</item>
<item>spec://connectorE75:TestProcedures:AllAccessories/*</item>
<item>spec://connectorC89C91:MechanicalRequirements:All/*</item>
<item>spec://accessoryAll:FeatureDuplication/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12CLK0020</internal>
</entry>
<entry label="accessoryAll:MinimumDeviceCompatibility" type="section">
<index>2.1</index>
<name>Minimum Device Compatibility</name>
<keywords>exclusion,exclude,manner,6th generation,pro,compatibility,inch,ipad</keywords>
<related>
<item>spec://componentAuthCP20C:DeviceCharacteristics:DCElectricalCharacteristics/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0022</internal>
</entry>
<entry label="accessoryAll:TestingWithAppleBetaSoftware" type="section">
<index>2.2</index>
<name>Testing with Apple Beta Software</name>
<keywords>reproducibility,investigation,reproduction,workaround,membership,reporter,apple beta software,beta software access,website</keywords>
<related>
<item>spec://accessoryAll:TestingWithAppleBetaSoftware:BetaSoftwareAccessAndInstallation/*</item>
<item>spec://accessoryAll:TestingWithAppleBetaSoftware:IssueReporting/*</item>
<item>spec://componentAuthCP20C:AuthenticationProtocol/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0023</internal>
</entry>
<entry label="accessoryAll:TestingWithAppleBetaSoftware:BetaSoftwareAccessAndInstallation" type="section">
<index>2.2.1</index>
<name>Beta Software Access and Installation</name>
<keywords>membership,beta software access,installation,program,obtain,separate,developer</keywords>
<related>
<item>spec://transportBluetooth:TestProcedures:iAP:CapturingiAPoverBluetooth/*</item>
<item>spec://accessoryAll:TestingWithAppleBetaSoftware/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0024</internal>
</entry>
<entry label="accessoryAll:TestingWithAppleBetaSoftware:ProfilesAndLogs" type="section">
<index>2.2.2</index>
<name>Profiles and Logs</name>
<keywords>install,beta,log,bug,restart,software,profile,ios,bluetooth,recommend</keywords>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0025</internal>
</entry>
<entry label="accessoryAll:TestingWithAppleBetaSoftware:IssueReporting" type="section">
<index>2.2.3</index>
<name>Issue Reporting</name>
<keywords>reproducibility,investigation,reproduction,workaround,reporter,website,reproduce,crash,approximate,one bug report</keywords>
<related>
<item>spec://protocoliAP2:Link:SynchronizationPayload:RetransmissionTimeout/*</item>
<item>spec://accessoryAll:TestingWithAppleBetaSoftware/*</item>
<item>spec://componentAuthCP20C:AuthenticationProtocol/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0026</internal>
</entry>
<entry label="accessoryAll:DevelopmentToolsAndEmulators" type="section">
<index>2.3</index>
<name>Development Tools and Emulators</name>
<keywords>development tools,emulator,emulate,prohibit,intend,create,developer,manufacturer</keywords>
<related>
<item>spec://accessoryAll:OTATestingTISEISforAllBands/*</item>
<item>spec://accessoryAll:TestProcedures:OTA:Procedure/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0027</internal>
</entry>
<entry label="accessoryAll:ReferenceDesignsAndDevelopmentKits" type="section">
<index>2.4</index>
<name>Reference Designs &amp; Development Kits</name>
<keywords>prototype,reference designs,development kits,audit,warning,assist</keywords>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0028</internal>
</entry>
<entry label="accessoryAll:AccessoryAuthenticationandAccessoryIdentification" type="section">
<index>2.5</index>
<name>Accessory Authentication and Accessory Identification</name>
<keywords>simple,accessory authentication,accessory identification,authenticate,charger,sync,identify</keywords>
<related>
<item>spec://moduleX533:I2CInterfaceAccessoryAuthenticationAndIdentification/*</item>
<item>spec://featureAccessoryAuthentication:Examples:TypicalAccessoryAuthentication/*</item>
<item>spec://featureCarPlay:CarPlayCommunicationProtocol:ExampleInputReportLayoutForSimpleMedia/*</item>
<item>spec://protocolHID:Requirements:HIDNativeTransport(Bluetooth)/*</item>
<item>spec://featureAccessoryAuthentication:Requirements/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0029</internal>
</entry>
<entry label="accessoryAll:ConnectorModifications" type="section">
<index>2.6</index>
<name>Connector Modifications</name>
<keywords>modification,modify,direct,connector</keywords>
<related>
<item>spec://connectorUSBAReceptacle:TestProcedures:SI:HS:PassFailCriteria/*</item>
<item>spec://connectorUSBCReceptacle:TestProcedures:SI:HS:PassFailCriteria/*</item>
<item>spec://connectorUSBAReceptacle:TestProcedures:SI:HS/*</item>
<item>spec://connectorUSBCReceptacle:TestProcedures:SI:HS/*</item>
<item>spec://transportBluetooth:ServiceDiscoveryProtocol/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0030</internal>
</entry>
<entry label="accessoryAll:ConnectorAssemblies" type="section">
<index>2.7</index>
<name>Connector Assemblies</name>
<keywords>detachable,assembly,dongle,dock,case,define,implement,connector,lightning,page</keywords>
<related>
<item>spec://moduleX890:ConnectionMethods/*</item>
<item>spec://transportUSB:DeviceMode:USBEmbeddedHost/*</item>
<item>spec://accessoryDongles:E75Dongles/*</item>
<item>spec://accessoryDongles:ProductDesign/*</item>
<item>spec://moduleX890:LightningInterface/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0031</internal>
</entry>
<entry label="accessoryAll:AdaptersAndProxies" type="section">
<index>2.8</index>
<name>Adapters and Proxies</name>
<keywords>proxy,facilitate,compliant,product,connection,device</keywords>
<related>
<item>spec://transportUSB:USBHostModePassthroughs/*</item>
<item>spec://transportBluetooth:ServiceDiscoveryProtocol/*</item>
<item>spec://accessoryAll/*</item>
<item>spec://accessoryCases:Acoustics:SpeakerToMicrophoneCoupling/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0032</internal>
</entry>
<entry label="accessoryAll:MixedHeadsetAndE75Connectors" type="section">
<index>2.9</index>
<name>Mixed Headset Jack and Lightning Connectors</name>
<keywords>mixed headset jack,lightning connectors,attach,device</keywords>
<related>
<item>spec://featureDevicePowerE75:TestProcedures:DirectPowerSources:OutputVoltageRegulation/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0033</internal>
</entry>
<entry label="accessoryAll:AppleUSBPowerAdapters" type="section">
<index>2.10</index>
<name>Apple USB Power Adapters</name>
<keywords>apple usb power,weight,outlet,wall,plug,support,device</keywords>
<related>
<item>spec://featureDevicePowerE75:TestProcedures:Charging/*</item>
<item>spec://accessoryGameControllers:HIDRequirements:HIDGameControllerRequirements:ProductDesign:WeightAndBalance/*</item>
<item>spec://accessoryGameControllers:HIDRequirements:HIDGameControllerRequirements:ProductDesign/*</item>
<item>spec://featureDevicePowerE75:ExternalPowerSource/*</item>
<item>spec://accessoryGameControllers/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0034</internal>
</entry>
<entry label="accessoryAll:AppleWatchMagneticChargingCable" type="section">
<index>2.11</index>
<name>Apple Watch Magnetic Charging Cable</name>
<keywords>watch,magnetic,charge,claim,integrate,apple,module,require,supply,cable</keywords>
<related>
<item>spec://featureDevicePowerE75:TestProcedures:AWatchChargingCable/*</item>
<item>spec://moduleC62:Magnetic%20Charging%20Module/*</item>
<item>spec://featureDevicePowerOrion:Example/*</item>
<item>spec://moduleC62:TestProcedures:Electrical:ExternalUSBPowerSources:TestSetup/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0035</internal>
</entry>
<entry label="accessoryAll:AppleWatchLug" type="section">
<index>2.12</index>
<name>Apple Watch Lug</name>
<keywords>lug,distributor,guideline,accordance,watch,custom,integration,band,design</keywords>
<related>
<item>spec://connectorUSBCPlug:Mechanical/*</item>
<item>spec://connectorUSBCReceptacle:Mechanical/*</item>
<item>spec://connectorUSBCPlug/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0036</internal>
</entry>
<entry label="accessoryAll:DeviceDetection" type="section">
<index>2.13</index>
<name>Device Detection</name>
<keywords>byte sequence,detection,assume,accessory power,offer,respond,choose,implement</keywords>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0037</internal>
</entry>
<entry label="accessoryAll:MultipleSimultaneousiAP2Connections" type="section">
<index>2.14</index>
<name>Multiple Simultaneous iAP2 Connections</name>
<keywords>multiple simultaneous,determination,specific feature,compare,same device,shut,wired,transport</keywords>
<related>
<item>spec://accessoryAll/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0038</internal>
</entry>
<entry label="accessoryAll:Disconnecting and Reconnecting" type="section">
<index>2.15</index>
<name>Disconnecting and Reconnecting</name>
<keywords>reconnect,disconnect,role,initiate,direct,action,switch,case,connection,carplay</keywords>
<related>
<item>spec://transportBluetooth:TestProcedures:Reconnection:ReconnectfromDevice/*</item>
<item>spec://transportBluetooth:TestProcedures:Reconnection:ReconnectfromAccessory/*</item>
<item>spec://featureCarPlay:GeneralRequirements:Architecture:CarPlayOverWireless:Session%20Termination:Direct%20User%20Action/*</item>
<item>spec://protocoliAP2:Link:Operation:Reset/*</item>
<item>spec://featureCarPlay:GeneralRequirements:Architecture:CarPlayOverWireless:Session%20Termination/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0039</internal>
</entry>
<entry label="accessoryAll:DeviceStatusUpdates" type="section">
<index>2.16</index>
<name>Device Status Updates</name>
<keywords>life,infer,buildup,thermal,processor,query,acceptable,poll,impact,performance</keywords>
<related>
<item>spec://transportBluetoothLowEnergy:DataPacketLengthExtension/*</item>
<item>spec://transportBluetooth:Profiles:AudioVideoRemoteControlProfile:PlayOrPauseButton/*</item>
<item>spec://componentMikeyTransmitter:ThermalImpedance/*</item>
<item>spec://moduleX890:32bitMCUDSPSubsystem/*</item>
<item>spec://componentAuthCP20C:SignalsAndPinouts/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0040</internal>
</entry>
<entry label="accessoryAll:PresentationofDeviceState" type="section">
<index>2.17</index>
<name>Presentation of Device Updates</name>
<keywords>state change,actuate,hid usage,presentation,device updates,problem,happen,exact,cache,prohibit</keywords>
<related>
<item>spec://featureWAC:Bonjour:MFIConfigurationStatusFlag/*</item>
<item>spec://CarPlayParameterValueTable:bitfield:featuresCarPlay:StatusFlags/*</item>
<item>spec://Introduction:Terminology:DUA/*</item>
<item>spec://featureCarPlay:CarPlayCommunicationProtocol:Commands:forceKeyFrame/*</item>
<item>spec://transportBluetooth:Profiles:AudioVideoRemoteControlProfile:Notifications/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0042</internal>
</entry>
<entry label="accessoryAll:RelationshipsBetweenMultipleAccessories" type="section">
<index>2.18</index>
<name>Relationships Between Multiple Accessories</name>
<keywords>multiple accessories,relationship,responsible,behalf,individual,inactive,situation,manage,component</keywords>
<related>
<item>spec://CarPlay:CarPlayCommunicationProtocol:SetupAndControl:Synchronization:MediaClockSynchronization/*</item>
<item>spec://featureCarPlay:CarPlayCommunicationProtocol:SetupandControl:Synchronization/*</item>
<item>spec://moduleX533:I2CInterfaceAccessoryAuthenticationAndIdentification/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0043</internal>
</entry>
<entry label="accessoryAll:iBeacon" type="section">
<index>2.19</index>
<name>iBeacon</name>
<keywords>feature,support</keywords>
<related>
<item>spec://iAP2MessageParameterList:NowPlayingUpdate/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0044</internal>
</entry>
<entry label="accessoryAll:FeatureDuplication" type="section">
<index>2.20</index>
<name>Feature Duplication</name>
<keywords>duplication,overlap,kind,functionality,midi,addition,offer,mechanism,feature,implement</keywords>
<related>
<item>spec://accessoryAll/*</item>
<item>spec://transportWiFi:TestProceduresfortheConsumers:OtherScenarios:Longevity/*</item>
<item>spec://featureWAC:WACRequirements/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0045</internal>
</entry>
<entry label="accessoryAll:TemperatureRange" type="section">
<index>2.21</index>
<name>Temperature Range</name>
<keywords>publish,temperature,range,equal,compatibility,claim,device</keywords>
<related>
<item>spec://componentAuthCP3.0:RecommendedOperatingConditions:Table/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0046</internal>
</entry>
<entry label="accessoryAll:IntegratedUSBReceptacles" type="section">
<index>2.22</index>
<name>Integrated USB Receptacles or Lightning Receptacle (C37)</name>
<keywords>integrated usb receptacles,compliant,providing power,drawing,lightning receptacle,comply,brand,purpose</keywords>
<related>
<item>spec://featureDevicePowerE75:DirectPowerSource:OtherConnectors/*</item>
<item>spec://accessoryDocks:FlexibleMechanism/*</item>
<item>spec://featureDevicePowerE75:DirectPowerSource/*</item>
<item>spec://featureDevicePowerE75:C37PassthroughPower/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0047</internal>
</entry>
<entry label="accessoryAll:IntegratedNonUSBReceptacles" type="section">
<index>2.23</index>
<name>Integrated Non-USB Receptacles</name>
<keywords>included,firewire,highlight,hdmi,respective,manner,thunderbolt,compliant,carry,accordance</keywords>
<related>
<item>spec://accessoryCables:All/*</item>
<item>spec://featureCarPlay:GeneralRequirements:Architecture/*</item>
<item>spec://CarPlayMessageParameterTable:featuresCarPlay:UserPreferences/*</item>
<item>spec://componentMikeyTransmitter:Requirements/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0048</internal>
</entry>
<entry label="accessoryAll:UserSuppliedCablesAndPowerAdapters" type="section">
<index>2.24</index>
<name>User Supplied Cables and AC Power Adapters</name>
<keywords>clearance,surround,compliant connector,supplied cables,sufficient,accommodate,regard,aspect</keywords>
<related>
<item>spec://featureCarPlay:GeneralRequirements:HardwareRequirements:HighResolutionDisplay/*</item>
<item>spec://featureMediaLibrary:Requirements/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0050</internal>
</entry>
<entry label="accessoryAll:RemovableStorage" type="section">
<index>2.25</index>
<name>Removable Storage</name>
<keywords>removable,reader,storage,dakota,card,external accessory protocol,integrate,component</keywords>
<related>
<item>spec://connectorHeadsetPlug:TestProcedures/*</item>
<item>spec://connectorHeadsetPlug/*</item>
<item>spec://accessoryAll:Attachments/*</item>
<item>spec://featureExternalAccessoryProtocol:TestProcedures:ExternalAccessoryProtocoloverNative/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0051</internal>
</entry>
<entry label="accessoryAll:TDMANoise" type="section">
<index>2.26</index>
<name>TDMA Noise</name>
<keywords>electronics,division,chopper,couple,radiate,conduct,produce,interference,audible,emit</keywords>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0052</internal>
</entry>
<entry label="accessoryAll:Attachments" type="section">
<index>2.27</index>
<name>Attachments</name>
<keywords>scanner,barcode,desk,case accessory,mat,reader,credit,attachment,detachable,compliant</keywords>
<related>
<item>spec://accessoryAll:RemovableStorage/*</item>
<item>spec://accessoryAirPodsAttachments:Interference/*</item>
<item>spec://accessoryAirPodsAttachments/*</item>
<item>spec://accessoryCases:PD:QiWirelessPowerandRearPockets/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0053</internal>
</entry>
<entry label="accessoryAll:MagneticInterference" type="section">
<index>2.28</index>
<name>Magnetic Interference</name>
<keywords>recalibration,magnetometer,autofocus,optical,digital compass,metal,rear,image</keywords>
<related>